version: '3.1'
services:
  assessment_db:
    image: postgres:14-alpine
    container_name: dev_assessment_db
    environment:
      POSTGRES_USER: main
      POSTGRES_PASSWORD: main
      POSTGRES_DB: main
    volumes:
      - temp_main:/var/lib/postgresql/data
    ports:
      - "4000:5432"
  test_db:
    image: postgres:14-alpine
    container_name: test_db
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: main_test
    volumes:
      - temp_test:/var/lib/postgresql/data
    ports:
      - "4001:5432"
volumes:
  temp_main:
  temp_test: