version: '3.1'
services:
  assessment_db:
    image: postgres:13-alpine
    container_name: dev_assessment_db
    environment:
      POSTGRES_USER: main
      POSTGRES_PASSWORD: main
      POSTGRES_DB: main
    volumes:
      - main:/var/lib/postgresql/data
    ports:
      - "4000:5432"
  test_db:
    image: postgres:13-alpine
    container_name: test_db
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: main_test
    volumes:
      - test:/var/lib/postgresql/data
    ports:
      - "4001:5432"
volumes:
  main:
  test: