// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	CreateCompany(ctx context.Context, arg CreateCompanyParams) (CompanyDetail, error)
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error)
	CreatePaymentDetail(ctx context.Context, arg CreatePaymentDetailParams) (PaymentDetail, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteCompany(ctx context.Context, arg DeleteCompanyParams) error
	DeleteCustomer(ctx context.Context, arg DeleteCustomerParams) error
	DeletePaymentDetail(ctx context.Context, arg DeletePaymentDetailParams) error
	DeleteUser(ctx context.Context, id int64) error
	GetACompanyPaymentDetailByID(ctx context.Context, arg GetACompanyPaymentDetailByIDParams) (PaymentDetail, error)
	GetCompaniesCreatedByUser(ctx context.Context, arg GetCompaniesCreatedByUserParams) ([]CompanyDetail, error)
	GetCompany(ctx context.Context, id int64) (CompanyDetail, error)
	GetCompanyCreatedByUser(ctx context.Context, arg GetCompanyCreatedByUserParams) (CompanyDetail, error)
	GetCustomerByEmail(ctx context.Context, arg GetCustomerByEmailParams) (Customer, error)
	GetCustomerByID(ctx context.Context, arg GetCustomerByIDParams) (Customer, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	ListAllCompanyPaymentDetails(ctx context.Context, arg ListAllCompanyPaymentDetailsParams) ([]PaymentDetail, error)
	ListCustomers(ctx context.Context, arg ListCustomersParams) ([]Customer, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	UpdateCompany(ctx context.Context, arg UpdateCompanyParams) (CompanyDetail, error)
	UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (Customer, error)
	UpdatePaymentDetail(ctx context.Context, arg UpdatePaymentDetailParams) (PaymentDetail, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
